# Generated by Django 4.0.5 on 2023-02-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TODO',
        ),
    ]
