# Generated by Django 4.0.4 on 2023-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_doctor_hospitalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='doctorName',
            field=models.CharField(max_length=10),
        ),
    ]
