# Generated by Django 4.0.4 on 2023-02-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_certificate_isverified_alter_certificate_doctorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(),
        ),
    ]
