# Generated by Django 4.0.4 on 2023-02-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_certificate_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='user',
            new_name='username',
        ),
    ]
