# Generated by Django 4.0.4 on 2023-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_user_certificate_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ticketid',
            field=models.CharField(default=1001, max_length=100),
        ),
    ]
