# Generated by Django 4.0.4 on 2023-02-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_dwonloadcertificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dwonloadCertificate',
            new_name='downloadCertificate',
        ),
    ]
