# Generated by Django 4.0.4 on 2023-02-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_dwonloadcertificate_downloadcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcertificate',
            name='slip_id',
            field=models.CharField(max_length=200),
        ),
    ]
